WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT 
SET SERVEROUTPUT ON
SET ECHO OFF
SET TERMOUT ON
SET VERIFY OFF
SET LINESIZE 1024
SET FEEDBACK OFF

PROMPT &&SCHEMA_NAME
PROMPT QUERY ON SCHEMA &&SCHEMA_NAME